services:
  notes_backend_app:
    container_name: notes_backend_app
    hostname: notes_backend_app
    env_file:
      - ./backend/.env
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - sqlite_data:/app/data
    restart: unless-stopped

volumes:
  sqlite_data:
