services:
  api:
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/notes.db
    restart: unless-stopped

volumes:
  sqlite_data:
