services:
  notes_backend_app:
    container_name: notes_backend_app
    hostname: notes_backend_app
    env_file:
      - ./backend/.env
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - sqlite_data:/app/data
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  sqlite_data:
  redis_data:
