"""initial

Revision ID: 47605fb6295d
Revises:
Create Date: 2025-05-05 08:39:04.798837

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "47605fb6295d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
