"""add token table

Revision ID: 9962bc117de5
Revises: beb2a16e8e61
Create Date: 2025-05-05 21:03:08.906830

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9962bc117de5"
down_revision: Union[str, None] = "beb2a16e8e61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jwt_token",
        sa.Column("jti", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fp", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("jti", name=op.f("pk_jwt_token")),
        sa.UniqueConstraint("fp", name=op.f("uq_jwt_token_fp")),
    )
    op.create_index(
        op.f("ix_jwt_token_expires_at"),
        "jwt_token",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_jwt_token_user_id"), "jwt_token", ["user_id"], unique=False
    )
    op.create_index(
        "ix_token_user_alive",
        "jwt_token",
        ["user_id", "revoked", "expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_token_user_alive", table_name="jwt_token")
    op.drop_index(op.f("ix_jwt_token_user_id"), table_name="jwt_token")
    op.drop_index(op.f("ix_jwt_token_expires_at"), table_name="jwt_token")
    op.drop_table("jwt_token")
    # ### end Alembic commands ###
