#!/bin/sh

# Script for filtering commit messages before creating it
# Checks the compliance with the format [SQR]

green_color="\033[1;32m"
red_color="\033[1;31m"
color_off="\033[0m"
blue_color="\033[1;34m"
yellow_color="\033[1;33m"

commit_msg_filepath="$1"
regex="^\[SQR\] "

error_msg="Commit message format must match regex: [SQR] ..."

commit_msg=$(cat "$commit_msg_filepath")

if [[ "$commit_msg" =~ $regex ]]; then
    echo -e "${green_color}Good Commit!${color_off}"
    exit 0
else
    echo -e "${red_color}Bad commit ${blue_color}$commit_msg${color_off}"
    echo -e "${yellow_color}$error_msg${color_off}"
    echo "commit-msg hook failed (add --no-verify to bypass)"
    exit 1
fi
